core/blog/api/v1/urls.py
from django.urls import path, include
from rest_framework import routers

from . import views


app_name = "api-v1"


router = routers.DefaultRouter()
router.register("post", views.PostViewSet, basename="post")

urlpatterns = []

urlpatterns += router.urls

core/blog/urls.py
from django.urls import path, include
from django.views.decorators.cache import cache_page
from . import views

app_name = "blog"

urlpatterns = [
    # template view urls
    path("index/", cache_page(60*3)(views.index), name="index"), #TOY VIEW OF PRE-MADE HTML TEMPLATE
    path("", cache_page(60*3)(views.PostListView.as_view()), name="post_list"),
    path("<str:slug>/<int:pk>/", views.PostView.as_view(), name="post_detail"),
    path("create/", views.PostCreateview.as_view(), name="create_post"),
    path(
        "update/<str:slug>/<int:pk>/",
        views.PostUpdateView.as_view(),
        name="post_update",
    ),
    path(
        "delete/<str:slug>/<int:pk>/",
        views.PostDeleteView.as_view(),
        name="post_delete",
    ),
    # api view urls
    path("api/v1/", include("blog.api.v1.urls")),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="BLOG PROJECT APIs",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path("admin/", admin.site.urls),
    # doc
    path(
        "swagger<format>/", schema_view.without_ui(cache_timeout=0), name="schema-json"
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
    # general auth
    path("api-auth/", include("rest_framework.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    # apps
    path("accounts/", include("accounts.urls")),
    path("", include("blog.urls")),
    path("comment/", include("comment.urls")),
]

core/blog/models.py
from django.urls import reverse
from django.db import models

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=250)

    class Meta:
        verbose_name = "category"
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name


class Post(models.Model):
    author = models.ForeignKey(
        "accounts.Profile", on_delete=models.CASCADE, related_name="post"
    )
    title = models.CharField(max_length=50)
    slug = models.SlugField(unique=True)
    category = models.ManyToManyField("blog.Category", related_name="cat_post")
    banner = models.ImageField(blank=True, null=True)
    body = models.TextField()
    status = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField(blank=True, null=True)

    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={"pk": self.id, "slug": self.slug})

    def __str__(self):
        return self.title

core/blog/forms.py
from django import forms
from blog.models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            "title",
            "slug",
            "category",
            "banner",
            "body",
        )

core/blog/api/v1/views.py
from rest_framework.viewsets import ModelViewSet
from rest_framework.parsers import MultiPartParser, FormParser
from django_filters.rest_framework import DjangoFilterBackend

from blog.models import Post
from .serializers import PostSerializer
from .permissions import IsOwnerOrReadOnly


class PostViewSet(ModelViewSet):
    model = Post
    serializer_class = PostSerializer
    permission_classes = [
        IsOwnerOrReadOnly,
    ]
    parser_classes = [
        MultiPartParser,
        FormParser,
    ]
    filter_backends = [DjangoFilterBackend,]
    filterset_fields = ['category', 'author']

    def get_queryset(self):
        posts = Post.objects.filter(status=True)
        return posts

    def get_parsers(self):
        if getattr(self, "swagger_fake_view", False):
            return []
        return super().get_parsers()

core/blog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from typing import Any
from django.db.models.base import Model as Model
from django.db.models.query import QuerySet
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.forms import BaseModelForm
from django.http import HttpRequest, HttpResponse
from django.views import View
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from django.views.generic.edit import FormMixin
from .models import Post
from .forms import PostForm
from accounts.models.profile import Profile
from accounts.forms import SubForm
from comment.forms import CommentForm
from comment.views import CommentFormView

# Create your views here.


def index(request):
    return render(request, "index.html")


class PostListView(ListView):
    """
    template and CB view for listing Posts
    """

    model = Post
    template_name = "blog/post_list.html"
    context_object_name = "post_list"

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['form'] = SubForm()
        return data

    def get_queryset(self) -> QuerySet[Any]:
        posts = Post.objects.filter(status=True)
        return posts


class PostDetailView(DetailView):
    model = Post
    context_object_name = "post"
    template_name = "blog/post_detail.html"
    slug_url_kwarg = "slug"
    slug_field = "slug"
    query_pk_and_slug = True

    def get_queryset(self) -> QuerySet[Any]:
        return super().get_queryset().filter(status=True)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm()
        return context

class PostView(View):

    def get(self, request, *args, **kwargs):
        view = PostDetailView.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = CommentFormView.as_view()
        form = CommentForm(request.POST)
        # Set the current user
        # to the comment_author field
        form.instance.author = Profile.objects.get(user=request.user)
        # Set the blog post as the current blogpost
        form.instance.post = Post.objects.get(id=self.kwargs['pk'])
        form.instance.status = False
        if form.is_valid():
            form.save()
        return view(request, *args, **kwargs)



class PostCreateview(CreateView, PermissionRequiredMixin):
    model = Post
    permission_required = "blog.add_post"
    fields = ("title", "slug", "banner", "body", "category")
    template_name = "blog/post_create.html"

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        self.object = form.save(commit=False)
        self.object.author = Profile.objects.get(user=self.request.user)
        return super().form_valid(form)


class PostUpdateView(UpdateView, PermissionRequiredMixin):
    model = Post
    template_name = "blog/post_update.html"
    permission_required = "blog.change_post"
    permission_denied_message = " you dont have the permission to edit a post in blog"
    fields = (
        "title",
        "slug",
        "banner",
        "body",
    )

    def get_queryset(self):
        query = super().get_queryset()
        return query.filter(author__user=self.request.user)


class PostDeleteView(DeleteView, PermissionRequiredMixin):
    model = Post
    template_name = "blog/post_delete.html"
    permission_required = "blog.delete_post"
    permission_denied_message = " you dont have the permission to delete this post"
    success_url = reverse_lazy("blog:post_list")
    context_object_name = "post"

    def get_queryset(self):
        query = super().get_queryset()
        return query.filter(author__user=self.request.user)

core/blog/templates/blog/post_create.html
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Create Post</button>
</form>

core/blog/templates/blog/post_delete.html
{% extends 'base.html' %}



{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ post }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>
{% endblock content %}
    

core/blog/templates/blog/post_detail.html
{% extends 'base.html' %}


{% block title %}
   {{post.title}} 
{% endblock title %}



{% block content %}
<p> {{post.title}} </p>
<p> {{post.author}} </p>
<p> {{post.created_date}} </p>
<img src="{{post.banner}}" alt="image does not loaded!!">
<p> {{post.body}} </p>

{% if post.author.user == request.user %}
<a href="{% url 'blog:post_update' slug=post.slug pk=post.id %}">Edit!</a>
<a href="{% url 'blog:post_delete' slug=post.slug pk=post.id %}">delete!</a>

<p> Comments:</p>
<p> ___________________________________</p>

{% for comment in post.comment.all %}

{% if comment.status == True %}
<p> {{comment.author}} </p>   

<p> {{comment.body}} </p>   
<p> ---------------------------------------------------------------</p>

{% endif %}
   

{% endfor %}
   
{% endif %}
<form method="post">
   {% csrf_token %}
   {{form.as_p}}
   <button type="submit">send</button>
</form>
   
    
{% endblock content %}
    
    

core/blog/templates/blog/post_list.html
{% extends "base.html" %}
{% load static %}


{% block title %}

post list 
    
{% endblock title %}
    
{% block content %}
    {% for post in post_list %}
    <div class="single-recent-blog-post">
        <div class="thumb">
          <img class="img-fluid" src="{% static 'blog/img/blog/blog2.png' %}" alt="">
          <ul class="thumb-info">
            <li><a href="#"><i class="ti-user"></i>{{post.author|slice:":7"}}</a></li>
            <li><a href="#"><i class="ti-notepad"></i>{{post.created_date}}</a></li>
            <li><a href="#"><i class="ti-themify-favicon"></i>2 Comments</a></li>
          </ul>
        </div>
        <div class="details mt-20">
            <a href="{{post.get_absolute_url}}">{{post.title}}</a>
            <p class="tag-list-inline">Tag: {% for category in post.category.all %} <a href="#">{{category.name}}</a>,
                {% endfor %}</p>
            <p>
                {{post.body|slice:":255"}}
            </p>

          <a class="button" href="{{post.get_absolute_url}}">Read More <i class="ti-arrow-right"></i></a>
        </div>
      </div>
    {% endfor %}
    
    <!-- start of blog post pagination -->

    <div class="row">
        <div class="col-lg-12">
            <nav class="blog-pagination justify-content-center d-flex">
                <ul class="pagination">
                    <li class="page-item">
                        <a href="#" class="page-link" aria-label="Previous">
                            <span aria-hidden="true">
                                <i class="ti-angle-left"></i>
                            </span>
                        </a>
                    </li>
                    <li class="page-item active"><a href="#" class="page-link">1</a></li>
                    <li class="page-item"><a href="#" class="page-link">2</a></li>
                    <li class="page-item">
                        <a href="#" class="page-link" aria-label="Next">
                            <span aria-hidden="true">
                                <i class="ti-angle-right"></i>
                            </span>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
      </div>
    </div> 
    <!-- end of blog post pagination -->
{% endblock content %}
    

core/blog/templates/blog/post_update.html
{% extends 'base.html' %}
{% block title %}
    Update Post    
{% endblock title %}

    

{% block content %}
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Update Post</button>
</form>
    
{% endblock content %}
    